title: "Brant: Foundation Model for Intracranial Neural Signal"
description: "Daoze Zhang *, Zhizhang Yuan *, Yang Yang â€ , Junru Chen, Jingjing Wang, Yafeng Li"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman